---
- name: Side effect playbook for Hx Insight Connector
  hosts: all
  tasks:
    - name: Include hxi_connector role
      ansible.builtin.include_role:
        name: alfresco.platform.hxi_connector
      vars:
        hxi_connector_remote_ingestion_url: "https://hxinsight.alfresco.com/ingestion"
        hxi_connector_remote_prediction_url: "https://hxinsight.alfresco.com/predictions"
        hxi_connector_remote_token_url: "https://hxinsight.alfresco.com/token"
        hxi_connector_remote_client_id: "client-id"
        hxi_connector_remote_client_secret: "client-secret"
        hxi_connector_remote_environment_key: "environment-key"
        hxi_connector_alfresco_base_url: "http://localhost:8080"
        hxi_connector_alfresco_username: "admin" # pragma: allowlist secret
        hxi_connector_alfresco_password: "admin" # pragma: allowlist secret
        hxi_connector_alfresco_sfs_url: "https://sfs.alfresco.com"
        hxi_connector_alfresco_activemq_url: "ssl://activemq.alfresco.com:61617"
        hxi_connector_service_user: "alfresco"
        hxi_connector_application_sourceid: "some-uuid-1234ab"

    - name: Include repository-extension
      ansible.builtin.include_role:
        name: alfresco.platform.hxi_connector
        tasks_from: repository-extension
      vars:
        hxi_connector_remote_discovery_url: "https://hxinsight.alfresco.com/discovery"
        hxi_connector_remote_prediction_url: "https://hxinsight.alfresco.com/predictions"
        hxi_connector_remote_token_url: "https://hxinsight.alfresco.com/token"
        hxi_connector_remote_client_id: "client-id"
        hxi_connector_remote_client_secret: "client-secret"
        hxi_connector_remote_environment_key: "environment-key"
        hxi_connector_application_sourceid: "some-uuid-1234ab"
