---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Populate service facts
      ansible.builtin.service_facts:

    - name: Check expected services are present
      ansible.builtin.assert:
        that:
          - "'alfresco-hxinsight-connector-live-ingester.service' in ansible_facts.services"
          - ansible_facts.services['alfresco-hxinsight-connector-live-ingester.service'].state == 'running'
          - "'alfresco-hxinsight-connector-prediction-applier.service' not in ansible_facts.services" # disabled by default
          - "'alfresco-hxinsight-connector-bulk-ingester.service' not in ansible_facts.services" # requires a postgres db

    - name: Ensure live-ingester service is running
      ansible.builtin.systemd:
        name: alfresco-hxinsight-connector-live-ingester
        state: started
      register: live_ingester_svc

    - name: Check side effect triggered proper service restart
      become: true
      changed_when: false
      ansible.builtin.command:
        cmd: >-
          grep -q 'SPRING_ACTIVEMQ_BROKERURL=ssl://activemq.alfresco.com:61617'
          /proc/{{ live_ingester_svc.status.ExecMainPID }}/environ

    - name: Check repository extension properties file is present
      ansible.builtin.slurp:
        src: >-
          /opt/alfresco/content-services-23.4.0/modules/acs-platform-config/alfresco/module/alfresco-hxinsight-connector-hxinsight-extension/alfresco-global.properties
      register: repository_extension_properties
      changed_when: false

    - name: Check repository extension properties file content is present
      vars:
        props: "{{ repository_extension_properties['content'] | b64decode }}"
      ansible.builtin.assert:
        that:
          - "'hxi.discovery.base-url=https://hxinsight.alfresco.com' in props"
          - "'hxi.connector.source-id=some-uuid-1234ab' in props"
        quiet: true
