---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Check live-ingester service is running
      ansible.builtin.systemd:
        name: alfresco-hxinsight-connector-live-ingester
        state: started
      register: live_ingester_svc

    - name: Check prediction-applier service is running
      ansible.builtin.systemd:
        name: alfresco-hxinsight-connector-prediction-applier
        state: started

    - name: Check side effect triggered proper service restart
      become: true
      changed_when: false
      ansible.builtin.command:
        cmd: >-
          grep -q 'SPRING_ACTIVEMQ_BROKERURL=ssl://activemq.alfresco.com:61617'
          /proc/{{ live_ingester_svc.status.ExecMainPID }}/environ

    - name: Check repository extension properties file is present
      ansible.builtin.slurp:
        src: /opt/alfresco/hxi-connector/repository-extension.properties
      register: repository_extension_properties
      changed_when: false

    - name: Check repository extension properties file content is present
      vars:
        props: "{{ repository_extension_properties['content'] | b64decode }}"
      ansible.builtin.assert:
        that:
          - "'hxi.discovery.base-url=https://hxinsight.alfresco.com' in props"
          - "'hxi.connector.source-id=some-uuid-1234ab' in props"
        quiet: true
