objects:
  role:
    hxi_connector:
      description: Install a Hx Insight Connector
      name: hxi_connector
      version_added: null
    java:
      description: Main entrypoint for the java role
      name: java
      version_added: null
    systemd_service:
      description: Install a systemd service unit
      name: systemd_service
      version_added: null
plugins:
  become: {}
  cache: {}
  callback: {}
  cliconf: {}
  connection: {}
  filter: {}
  httpapi: {}
  inventory: {}
  lookup: {}
  module: {}
  netconf: {}
  shell: {}
  strategy: {}
  test: {}
  vars: {}
version: 0.1.0
