galaxy_info:
  author: Alfresco Ops Readiness
  namespace: alfresco
  description: Install and configure Hx Insights Connector
  company: Hyland Software

  license: Apache-2.0

  min_ansible_version: "2.16"

  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
    - name: EL
      versions:
        - "8"
        - "9"

  galaxy_tags:
    - alfresco

dependencies: []
