---
# required variables
hxi_connector_artifact_username: ''
hxi_connector_artifact_password: ''

hxi_connector_java_home_path: /opt/openjdk-17.0.15
hxi_connector_java_bin_path: "{{ hxi_connector_java_home_path }}/bin/java"

hxi_connector_artifact_base_path: /opt/alfresco/hxi-connector
hxi_connector_artifact_repository_url: https://nexus.alfresco.com/nexus/repository/releases/
hxi_connector_artifact_default_version: 2.0.2

## bulk ingester section
hxi_connector_bulk_ingester_artifact_name: alfresco-hxinsight-connector-bulk-ingester
hxi_connector_bulk_ingester_artifact_version: "{{ hxi_connector_artifact_default_version }}"
hxi_connector_bulk_ingester_artifact_url: "{{ hxi_connector_artifact_repository_url }}/org/alfresco/\
  {{ hxi_connector_bulk_ingester_artifact_name }}/{{ hxi_connector_bulk_ingester_artifact_version }}/\
  {{ hxi_connector_bulk_ingester_artifact_name }}-{{ hxi_connector_bulk_ingester_artifact_version }}-app.jar"
hxi_connector_bulk_ingester_artifact_path: >-
  {{ hxi_connector_artifact_base_path }}/{{ hxi_connector_bulk_ingester_artifact_name }}-{{ hxi_connector_bulk_ingester_artifact_version }}-app.jar
hxi_connector_bulk_ingester_port: 8082

## live ingester section
hxi_connector_live_ingester_artifact_name: alfresco-hxinsight-connector-live-ingester
hxi_connector_live_ingester_artifact_version: "{{ hxi_connector_artifact_default_version }}"
hxi_connector_live_ingester_artifact_url: "{{ hxi_connector_artifact_repository_url }}/org/alfresco/\
  {{ hxi_connector_live_ingester_artifact_name }}/{{ hxi_connector_live_ingester_artifact_version }}/\
  {{ hxi_connector_live_ingester_artifact_name }}-{{ hxi_connector_live_ingester_artifact_version }}-app.jar"
hxi_connector_live_ingester_artifact_path: >-
  {{ hxi_connector_artifact_base_path }}/{{ hxi_connector_live_ingester_artifact_name }}-{{ hxi_connector_live_ingester_artifact_version }}-app.jar
hxi_connector_live_ingester_port: 8080
hxi_connector_alfresco_version_override: 23.4.0

## prediction applier section
hxi_connector_prediction_applier_enabled: false
hxi_connector_prediction_applier_artifact_name: alfresco-hxinsight-connector-prediction-applier
hxi_connector_prediction_applier_artifact_version: "{{ hxi_connector_artifact_default_version }}"
hxi_connector_prediction_applier_artifact_url: "{{ hxi_connector_artifact_repository_url }}/org/alfresco/\
  {{ hxi_connector_prediction_applier_artifact_name }}/{{ hxi_connector_prediction_applier_artifact_version }}/\
  {{ hxi_connector_prediction_applier_artifact_name }}-{{ hxi_connector_prediction_applier_artifact_version }}-app.jar"
hxi_connector_prediction_applier_artifact_path: >-
  {{ hxi_connector_artifact_base_path }}/{{ hxi_connector_prediction_applier_artifact_name }}-{{ hxi_connector_prediction_applier_artifact_version }}-app.jar
hxi_connector_prediction_applier_port: 8081

## repository extension section
hxi_connector_repository_extension_artifact_name: alfresco-hxinsight-connector-hxinsight-extension
hxi_connector_repository_extension_artifact_version: "{{ hxi_connector_artifact_default_version }}"
hxi_connector_repository_extension_artifact_url: "{{ hxi_connector_artifact_repository_url }}/org/alfresco/\
  {{ hxi_connector_repository_extension_artifact_name }}/{{ hxi_connector_repository_extension_artifact_version }}/\
  {{ hxi_connector_repository_extension_artifact_name }}-{{ hxi_connector_repository_extension_artifact_version }}.jar"
hxi_connector_repository_extension_acs_version: "{{ hxi_connector_alfresco_version_override }}"
hxi_connector_repository_extension_modules_path: "/opt/alfresco/content-services-{{ hxi_connector_repository_extension_acs_version }}/modules"
hxi_connector_repository_extension_artifact_path: "{{ hxi_connector_repository_extension_modules_path }}/acs-platform/\
  {{ hxi_connector_repository_extension_artifact_name }}.jar"
hxi_connector_repository_extension_properties_snippet_path: "{{ hxi_connector_repository_extension_modules_path }}/acs-platform-config/\
  alfresco/module/alfresco-hxinsight-connector-hxinsight-extension/alfresco-global.properties"
hxi_connector_repository_extension_owner: alfresco
hxi_connector_repository_extension_group: alfresco

## Alfresco section
hxi_connector_alfresco_activemq_username: ''
hxi_connector_alfresco_activemq_password: ''
hxi_connector_alfresco_db_url: ''
hxi_connector_alfresco_db_username: ''
hxi_connector_alfresco_db_password: ''
hxi_connector_alfresco_service_existing_handler_name: ''
hxi_connector_alfresco_service_name: alfresco-content-monitored-startup
hxi_connector_alfresco_base_url: ''
hxi_connector_alfresco_username: ''
hxi_connector_alfresco_password: ''
hxi_connector_alfresco_sfs_url: ''
hxi_connector_alfresco_activemq_url: ''
hxi_connector_application_sourceid: ''

## Remote section
hxi_connector_remote_discovery_url: ''
hxi_connector_remote_ingestion_url: ''
hxi_connector_remote_token_url: ''
hxi_connector_remote_prediction_url: ''
hxi_connector_remote_client_id: ''
hxi_connector_remote_client_secret: ''
hxi_connector_remote_environment_key: ''
hxi_connector_remote_grant_type: "urn:hyland:params:oauth:grant-type:api-credentials"
