---
# defaults file for search_index
search_index_version: 5.7.0-A.5
search_index_artifact_name: alfresco-elasticsearch-batch-indexing-distribution
search_index_repository: https://nexus.alfresco.com/nexus/content/repositories/releases/org/alfresco
search_index_zip_url: "{{ search_index_repository }}/{{ search_index_artifact_name }}/{{ search_index_version }}/{{ search_index_artifact_name }}-{{ search_index_version }}.zip" # noqa yaml[line-length]
search_index_zip_checksum: sha1:{{ search_index_zip_url }}.sha1

search_index_download_location: /tmp
search_index_nexus_username: ''
search_index_nexus_password: ''

search_index_acs_version: "26.2.0"

search_index_username: alfresco
search_index_group_name: alfresco

search_index_server_port: 8080

search_index_elasticsearch_url: http://localhost:9200
search_index_elasticsearch_username: ''
search_index_elasticsearch_password: ''
search_index_elasticsearch_index_name: alfresco

search_index_db_url: jdbc:postgresql://localhost:5432/alfresco
search_index_db_username: alfresco
search_index_db_password: ''

search_index_acs_url: http://localhost:8080
search_index_content_transform_shared_secret: ''

search_index_default_environment:
  SERVER_PORT: "{{ search_index_server_port }}"
  SPRING_ELASTICSEARCH_REST_URIS: "{{ search_index_elasticsearch_url }}"
  SPRING_ELASTICSEARCH_REST_USERNAME: "{{ search_index_elasticsearch_username }}"
  SPRING_ELASTICSEARCH_REST_PASSWORD: "{{ search_index_elasticsearch_password }}"
  ELASTICSEARCH_INDEXNAME: "{{ search_index_elasticsearch_index_name }}"
  SPRING_DATASOURCE_URL: "{{ search_index_db_url }}"
  SPRING_DATASOURCE_USERNAME: "{{ search_index_db_username }}"
  SPRING_DATASOURCE_PASSWORD: "{{ search_index_db_password }}"
  ALFRESCO_ACS_URL: "{{ search_index_acs_url }}"
  ALFRESCO_CONTENT_TRANSFORM_SHAREDSECRET: "{{ search_index_content_transform_shared_secret }}"
search_index_environment: {}

search_index_java_home_path: /opt/java
search_index_java_bin_path: "{{ search_index_java_home_path }}/bin/java"

search_index_binaries_dir: "/opt/alfresco/batch-indexing-{{ search_index_version }}"
search_index_config_dir: "/etc/alfresco/batch-indexing"

search_index_packages:
  - unzip

search_index_systemd_service_unit_name: "alfresco-batch-indexing"
search_index_systemd_service_unit_description: "Alfresco Elasticsearch Batch Indexing"
search_index_systemd_service_exec_start: "{{ search_index_java_bin_path }} -jar {{ search_index_artifact_path }}"
search_index_systemd_service_user: "{{ search_index_username }}"

search_index_systemd_service_unit_after: syslog.target network.target local-fs.target remote-fs.target nss-lookup.target
search_index_systemd_service_type: simple
search_index_systemd_service_exec_stop: kill -15 $MAINPID
search_index_systemd_service_working_directory: /tmp
search_index_systemd_service_additional_options: {}
search_index_systemd_service_state: started
search_index_systemd_service_enabled: true
