---
- name: Converge
  hosts: instance
  tasks:
    - name: Include java role
      ansible.builtin.include_role:
        name: alfresco.platform.java
    - name: Include main role
      ansible.builtin.include_role:
        name: alfresco.platform.audit_storage
      vars:
        audit_storage_nexus_username: "{{ lookup('env', 'NEXUS_USERNAME') }}"
        audit_storage_nexus_password: "{{ lookup('env', 'NEXUS_PASSWORD') }}"
        audit_storage_broker_url: failover:(tcp://activemq-instance:61616)
        audit_storage_opensearch_url: http://elasticsearch-instance:9200
