---
- name: Prepare
  hosts: instance
  become: true
  tasks:
    - name: Add an application group
      ansible.builtin.group:
        name: alfresco
        system: true
    - name: Add an application user
      ansible.builtin.user:
        name: alfresco
        system: true
        group: alfresco
