galaxy_info:
  author: Alfresco Ops Readiness
  namespace: alfresco
  description: Install and configure systemd services
  company: Hyland Software

  license: Apache-2.0

  min_ansible_version: "2.16"

  galaxy_tags:
    - systemd
    - service
    - configuration

  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
    - name: EL
      versions:
        - "8"
        - "9"
