- name: Fetch Live Ingester artifact for version {{ hxi_connector_live_ingester_artifact_version }}
  become: true
  become_user: "{{  hxi_connector_service_user }}"
  ansible.builtin.get_url:
    url: "{{ hxi_connector_live_ingester_artifact_url }}"
    dest: "{{ hxi_connector_live_ingester_artifact_path }}"
    url_username: "{{ hxi_connector_artifact_username }}"
    url_password: "{{ hxi_connector_artifact_password }}"
    mode: "0600"

- name: Set environments specific for Live Ingester
  ansible.builtin.set_fact:
    hxi_connector_live_ingester_environment:
      HYLANDEXPERIENCE_INSIGHT_INGESTION_BASEURL: "{{ hxi_connector_remote_ingestion_url }}"
      ALFRESCO_TRANSFORM_SHAREDFILESTORE_BASEURL: "{{ hxi_connector_alfresco_sfs_url }}"
      SERVER_PORT: "{{ hxi_connector_live_ingester_port }}"
      APPLICATION_SOURCEID: "{{ hxi_connector_application_sourceid }}"
      ALFRESCO_REPOSITORY_VERSIONOVERRIDE: "{{ hxi_connector_alfresco_version_override }}"

- name: Install Live Ingester
  ansible.builtin.include_role:
    name: alfresco.platform.systemd_service
    apply:
      become: true
  vars:
    systemd_service_unit_name: "alfresco-hxinsight-connector-live-ingester"
    systemd_service_unit_description: "Alfresco HXInsight Connector Live Ingester"
    systemd_service_exec_start: "{{ hxi_connector_java_bin_path }} -jar {{ hxi_connector_live_ingester_artifact_path }}"
    systemd_service_user: "{{ hxi_connector_service_user }}"
    systemd_service_environment: >-
      {{ hxi_connector_base_environment |
      combine(hxi_connector_remote_client_environment) |
      combine(hxi_connector_live_ingester_environment) }}
