- name: Ensure required variables are properly set
  ansible.builtin.assert:
    that:
      - hxi_connector_alfresco_base_url | length > 0
    fail_msg: "hxi_connector_alfresco_base_url must be defined"
    quiet: true

- name: Fetch Prediction Applier artifact for version {{ hxi_connector_prediction_applier_artifact_version }}
  become: true
  become_user: "{{  hxi_connector_service_user }}"
  ansible.builtin.get_url:
    url: "{{ hxi_connector_prediction_applier_artifact_url }}"
    dest: "{{ hxi_connector_prediction_applier_artifact_path }}"
    url_username: "{{ hxi_connector_artifact_username }}"
    url_password: "{{ hxi_connector_artifact_password }}"
    mode: "0600"

- name: Set environments specific for Prediction Applier
  ansible.builtin.set_fact:
    hxi_connector_prediction_applier_environment:
      HYLANDEXPERIENCE_INSIGHT_PREDICTIONS_BASEURL: "{{ hxi_connector_remote_prediction_url }}"
      SERVER_PORT: "{{ hxi_connector_prediction_applier_port }}"
      APPLICATION_SOURCEID: "{{ hxi_connector_application_sourceid }}"

- name: Install Prediction Applier
  ansible.builtin.include_role:
    name: alfresco.platform.systemd_service
    apply:
      become: true
  vars:
    systemd_service_unit_name: alfresco-hxinsight-connector-prediction-applier
    systemd_service_unit_description: "Alfresco HXInsight Connector Prediction Applier"
    systemd_service_exec_start: "{{ hxi_connector_java_bin_path }} -jar {{ hxi_connector_prediction_applier_artifact_path }}"
    systemd_service_user: "{{ hxi_connector_service_user }}"
    systemd_service_environment: >-
      {{ hxi_connector_base_environment |
      combine(hxi_connector_remote_client_environment) |
      combine(hxi_connector_prediction_applier_environment) }}
