name: Docs

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow}}-${{ github.ref_name }}
  cancel-in-progress: true

env:
  GHP_BASE_URL: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}

jobs:
  build:
    permissions:
      contents: read
    name: Build Ansible Docs
    uses: ansible-community/github-docs-build/.github/workflows/_shared-docs-build-push.yml@719619eaa6e76971b9eb3702c1d3cc3ac625c76b
    with:
      collection-name: alfresco.platform
      init-lenient: false
      init-fail-on-error: true
      squash-hierarchy: true
      init-project: Alfresco.Platform Collection
      init-copyright: Alfresco.Platform Contributors
      init-title: Alfresco.Platform Collection Documentation
      init-html-short-title: Alfresco.Platform Collection Docs
      init-extra-html-theme-options: |
        documentation_home_url=https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/branch/main/

  publish:
    if: github.repository == 'alfresco/alfresco-ansible-collection'
    permissions:
      contents: write
      pages: write
      id-token: write
    needs: build
    name: Publish Ansible Docs
    uses: ansible-community/github-docs-build/.github/workflows/_shared-docs-build-publish-gh-pages.yml@719619eaa6e76971b9eb3702c1d3cc3ac625c76b
    with:
      artifact-name: ${{ needs.build.outputs.artifact-name }}
      publish-gh-pages-branch: true
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  comment:
    name: PR comment
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    needs:
      - build
      - publish
    permissions:
      pull-requests: write
    steps:
      - name: PR comment
        uses: ansible-community/github-docs-build/actions/ansible-docs-build-comment@719619eaa6e76971b9eb3702c1d3cc3ac625c76b
        with:
          body-includes: '## Docs Build'
          reactions: heart
          action: ${{ needs.build.outputs.changed != 'true' && 'remove' || '' }}
          on-closed-action: remove
          on-merged-body: |
            ## Docs Build 📝

            Thank you for contribution!✨

            This PR has been merged and the docs are now incorporated into `main`:
            ${{ env.GHP_BASE_URL }}/branch/main
          body: |
            ## Docs Build 📝

            Thank you for contribution!✨

            The docs for **this PR** have been published here:
            ${{ env.GHP_BASE_URL }}/pr/${{ github.event.number }}

            You can compare to the docs for the `main` branch here:
            ${{ env.GHP_BASE_URL }}/branch/main

            The docsite for **this PR** is also available for download as an artifact from this run:
            ${{ needs.build.outputs.artifact-url }}

            File changes:

            ${{ needs.build.outputs.diff-files-rendered }}

            ${{ needs.build.outputs.diff-rendered }}
