name: Docs

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow}}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    permissions:
      contents: read
    name: Build Ansible Docs
    uses: ansible-community/github-docs-build/.github/workflows/_shared-docs-build-push.yml@719619eaa6e76971b9eb3702c1d3cc3ac625c76b
    with:
      collection-name: alfresco.platform
      init-lenient: false
      init-fail-on-error: true
      squash-hierarchy: true
      init-project: Alfresco.Platform Collection
      init-copyright: Alfresco.Platform Contributors
      init-title: Alfresco.Platform Collection Documentation
      init-html-short-title: Alfresco.Platform Collection Docs
      init-extra-html-theme-options: |
        documentation_home_url=https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/branch/main/

  publish:
    if: github.repository == 'alfresco/alfresco-ansible-collection'
    permissions:
      contents: write
      pages: write
      id-token: write
    needs: build
    name: Publish Ansible Docs
    uses: ansible-community/github-docs-build/.github/workflows/_shared-docs-build-publish-gh-pages.yml@719619eaa6e76971b9eb3702c1d3cc3ac625c76b
    with:
      artifact-name: ${{ needs.build.outputs.artifact-name }}
      publish-gh-pages-branch: true
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  comment:
    name: PR comment
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    needs: publish
    permissions:
      pull-requests: write
    steps:
      - name: Find existing comment
        uses: peter-evans/find-comment@3eae4d37986fb5a8592848f6a574fdf654e61f9e # v3.1.0
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Docs Build

      - name: Create comment
        if: steps.fc.outputs.comment-id == ''
        uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043 # v4.0.0
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            ## Docs Build 📝

            The docs for **this PR** have been published here:
            ${{ env.GHP_BASE_URL }}/pr/${{ github.event.number }}

            You can compare to the docs for the `main` branch here:
            ${{ env.GHP_BASE_URL }}/branch/main
        env:
          GHP_BASE_URL: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}
