name: Docs

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow}}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  docs-build:
    permissions:
      contents: read
    name: Build Ansible Docs
    uses: ansible-community/github-docs-build/.github/workflows/_shared-docs-build-push.yml@719619eaa6e76971b9eb3702c1d3cc3ac625c76b
    with:
      collection-name: alfresco.platform
      init-lenient: false
      init-fail-on-error: true
      squash-hierarchy: true
      init-project: Alfresco.Platform Collection
      init-copyright: Alfresco.Platform Contributors
      init-title: Alfresco.Platform Collection Documentation
      init-html-short-title: Alfresco.Platform Collection Docs
      init-extra-html-theme-options: |
        documentation_home_url=https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/

  docs-publish:
    if: github.repository == 'alfresco/alfresco-ansible-collection'
    permissions:
      contents: write
      pages: write
      id-token: write
    needs: docs-build
    name: Publish Ansible Docs
    uses: ansible-community/github-docs-build/.github/workflows/_shared-docs-build-publish-gh-pages.yml@719619eaa6e76971b9eb3702c1d3cc3ac625c76b
    with:
      artifact-name: ${{ needs.docs-build.outputs.artifact-name }}
      publish-gh-pages-branch: true
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
